name: nginx-sidecar-poc
services:
  router:
    build: .
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx/.conf:ro
      - ./nginx/routes.conf:/etc/nginx/conf.d/routes.conf
      - ./nginx/redirects.conf:/etc/nginx/conf.d/redirects.conf
    ports:
      - '8080:80'
      - '5000:5000'
    environment:
      - API_URL=http://router-api:3000
    depends_on:
      - router-api
      - http-echo-server-1
      - http-echo-server-2
  http-echo-server-1:
    extends:
      file: ../../manifests/http-echo.yml
      service: http-echo
    command: ["-text", "request has been proxied to http-echo-server-1"]
    ports:
      - 15678:5678
  http-echo-server-2:
    extends:
      file: ../../manifests/http-echo.yml
      service: http-echo
    command: ["-text", "request has been proxied to http-echo-server-2"]
    ports:
      - 15679:5678
  router-api:
    extends:
      file: ../router-api/manifest.yml
      service: router-api
    environment:
      - WEB_HOOK_URL=http://router:5000/update-config
